# Generated by Django 3.2.4 on 2021-06-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='grade',
            field=models.CharField(choices=[('P', 'P'), ('D', 'D'), ('M', 'M'), ('U', 'U')], default='U', max_length=50),
        ),
    ]
