# Generated by Django 3.2.4 on 2021-06-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_alter_materials_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materials',
            name='grade',
            field=models.CharField(choices=[('P', 'P'), ('U', 'U'), ('D', 'D'), ('M', 'M')], default='U', max_length=50),
        ),
    ]
